# Generated by Django 5.2.11 on 2026-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
