# Generated by Django 5.2.11 on 2026-02-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed')], error_messages={'invalid_choice': 'Status must be one of: scheduled, passed, or failed'}, max_length=10),
        ),
    ]
