# Generated by Django 5.2.11 on 2026-02-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed')], max_length=10),
        ),
    ]
